name: 'Build Godot Project'
description: 'Build a Godot project for multiple platforms'
inputs:
  name:
    description: 'Name of the exported package/binary'
    required: true
  preset:
    description: 'Name of the preset found in export_presets.cfg'
    required: true
  subdirectory:
    description: 'Subdirectory in build folder to output build'
    required: false
  package:
    description: 'Build artifact zip file'
    required: false
    default: 'false'
  projectDir:
    description: 'Directory containing your godot project'
    required: false
    default: '.'
  debugMode:
    description: 'Run export in debug mode'
    required: false
    default: 'false'
  headless:
    description: 'Run Godot in headless mode'
    required: false
    default: 'true'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.preset }}
    - ${{ inputs.subdirectory }}
    - ${{ inputs.package }}
    - ${{ inputs.projectDir }}
    - ${{ inputs.debugMode }}
    - ${{ inputs.headless }}
